apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
  namespace: ghost-tp
  labels:
    app.kubernetes.io/name: ghost-tp
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-nfs

